drop table T_CHILDREN;
drop table T_EMPLOYEES;
drop table T_KINDERGARTEN;
drop table T_GROUPS;
drop table  T_TYPES;
drop table  T_SERVICES_SCD;
drop table  T_SERVICES;
--drop table  T_ATTENDANCES;
drop table  T_LINKS_KID_GROUPS;
drop table  T_LINKS_SERVICE_TYPES;
DROP SEQUENCE DW_KINDERGARTEN_ID_seq; 
DROP SEQUENCE DW_TYPE_ID_seq ;
DROP SEQUENCE DW_children_id_seq; 
DROP SEQUENCE DW_group_id_seq ;
DROP SEQUENCE DW_employee_id_seq ;
DROP SEQUENCE DW_service_id_seq; 


CREATE TABLE T_CHILDREN(	
CHILD_ID        NUMBER          NOT NULL,
CONTRACT_NUM    NUMBER          NOT NULL,
FIRST_NAME      NVARCHAR2(50)   NOT NULL,
LAST_NAME       NVARCHAR2(50)   NOT NULL,
GENDER          CHAR(4)         NOT NULL,
PARENT_NAME_1   NVARCHAR2(50)   NOT NULL,
PARENT_NAME_2   NVARCHAR2(50)   NULL,
DATE_OF_BIRTH   DATE            NOT NULL,
PHONE_NUMBER    NVARCHAR2(50)   NULL,
INSERT_DT       TIMESTAMP        NOT NULL, 
UPDATE_DT       TIMESTAMP        NOT NULL,
CONSTRAINT DW_CHILD_PKEY PRIMARY KEY (CHILD_ID))
TABLESPACE dw_ts_data;

CREATE TABLE T_EMPLOYEES(   
EMPLOYEE_ID     NUMBER          NOT NULL,
CONTRACT_NUM    NUMBER          NOT NULL,
FIRST_NAME      NVARCHAR2(50)   NOT NULL,
LAST_NAME       NVARCHAR2(50)   NOT NULL,
PHONE_NUMBER    NVARCHAR2(50)   NULL,
EMAIL           NVARCHAR2(50)   NULL,
INSERT_DT       TIMESTAMP            NOT NULL, 
UPDATE_DT       TIMESTAMP            NOT NULL,
CONSTRAINT DW_EMPLOYEE_PKEY PRIMARY KEY (EMPLOYEE_ID))
TABLESPACE dw_ts_data ;

CREATE TABLE T_KINDERGARTEN(
KINDERGARTEN_ID NUMBER          NOT NULL,
KINDERGARTEN_DESC NVARCHAR2(50)   NOT NULL, --kindergarten
INSERT_DT       TIMESTAMP            NOT NULL, 
UPDATE_DT       TIMESTAMP            NOT NULL,
CONSTRAINT DW_GROUP_PKEY PRIMARY KEY (KINDERGARTEN_ID)
)TABLESPACE dw_ts_data;
 
CREATE TABLE T_GROUPS(   
GROUP_ID        NUMBER          NOT NULL,
GROUP_NUM       NUMBER         NOT NULL,
GROUP_DESC      NVARCHAR2(50)   NOT NULL, --kindergarten_groups
GROUP_SCALE     NUMBER(*,0)     NOT NULL,
INSERT_DT       TIMESTAMP       NOT NULL, 
UPDATE_DT       TIMESTAMP       NOT NULL,
CONSTRAINT DW_GROUPS_PKEY PRIMARY KEY (GROUP_ID)
)TABLESPACE dw_ts_data; 

CREATE TABLE T_LINKS_KID_GROUPS
(GROUP_ID        NUMBER          NOT NULL,
KINDERGARTEN_ID NUMBER          NOT NULL,
INSERT_DT       TIMESTAMP          NOT NULL, 
UPDATE_DT       TIMESTAMP            NOT NULL)
TABLESPACE dw_ts_data;

CREATE TABLE T_TYPES(
TYPE_ID             NUMBER      NOT NULL,
TYPE_DESC           NVARCHAR2(50) NOT NULL,--type
INSERT_DT       TIMESTAMP           NOT NULL, 
UPDATE_DT       TIMESTAMP           NOT NULL,
CONSTRAINT DE_SERVICE_SCD_PKEY PRIMARY KEY (TYPE_ID))
TABLESPACE dw_ts_data; 

CREATE TABLE T_SERVICES_SCD(
SERVICE_ID          NUMBER      NOT NULL,
SERVICE_DESC        NVARCHAR2(50) NOT NULL,--service
SERVICE_COST        FLOAT       NOT NULL,
TYPE_ID             NUMBER      NOT NULL,
START_FROM          DATE        NOT NULL, 
INSERT_DT      TIMESTAMP         NOT NULL, 
UPDATE_DT      TIMESTAMP          NOT NULL,
CONSTRAINT T_SERVICE_SCD_PKEY PRIMARY KEY (SERVICE_ID))
TABLESPACE dw_ts_data; 

CREATE TABLE T_LINKS_SERVICE_TYPES
(SERVICE_ID          NUMBER      NOT NULL,
TYPE_ID             NUMBER      NOT NULL,
START_FROM          DATE        NOT NULL)
TABLESPACE dw_ts_data; 

CREATE TABLE T_SERVICES(   
SERVICE_ID      NUMBER          NOT NULL,
SERVICE_DESC    NVARCHAR2(50)   NOT NULL,
INSERT_DT       TIMESTAMP           NOT NULL, 
UPDATE_DT       TIMESTAMP            NOT NULL
)TABLESPACE dw_ts_data; 


CREATE SEQUENCE DW_KINDERGARTEN_ID_seq; 
CREATE SEQUENCE DW_TYPE_ID_seq ;
CREATE SEQUENCE DW_children_id_seq; 
CREATE SEQUENCE DW_group_id_seq ;
CREATE SEQUENCE DW_employee_id_seq ;
CREATE SEQUENCE DW_service_id_seq  ; 